[book]
authors = ["Mohammad Al-aqua"]
language = "en"
src = "src"
title = "Introduction to Artificial Intelligence"


[output.html]
additional-css = ["theme/css/watermark.css"]

[preprocessor.katex]
after = ["links"]
output = "html"
block-delimiter = { left = "\\[", right = "\\]" }
inline-delimiter = { left = "\\(", right = "\\)" }
